### ISSUE TITLE
C++ completion not working properly

### ISSUE THREAD

**Issue by agauniyal** [kube/vscode-clang-complete#10]
I've attached an mp4 video[1] to show the difference between other clang based autocompletion vs this vscode-clang-complete. It works in the sense that it provides some unrelated completion items, but :
- doesn't provides all completions
- misses the essential ones that should be the first suggestions

[1] - https://vid.me/8gXY

**Comment by agauniyal** [comment]
This project - https://github.com/mitaki28/vscode-clang, although not made as language server in mind, does good job of producing good autocomplete results. Maybe you could take a look at it.

**Comment by kube** [comment]
It seems that `clang` when used for code completion uses `libstdc++` by default instead of `libc++`.

So I'm gonna see how to make it use `libc++` by default but I have to see how to make this properly.

So for now, you can specify `-stdlib=libc++` when using C++11 in the `.clang_complete` file.

I tested it on your `isaac-core` project:
[![Set -stdlib=libc++](https://img.youtube.com/vi/RtWg6P7mxNo/0.jpg)](https://www.youtube.com/watch?v=RtWg6P7mxNo)

**Comment by kube** [comment]
By the way you have a nice window manager.
Which one is it ?

**Comment by agauniyal** [comment]
Haha awesome :smile: . Currently I'm using bspwm - https://github.com/baskerville/bspwm. Dunno if it works on osx or not.

**Comment by agauniyal** [comment]
Nope, still not working, tried on 2 different machines, one Ubuntu and another arch linux. I've even removed all other plugins and tried it, shows few completions but they are of the form `__STDC__` . Maybe it has something to do with clang versions? Or any other requirements rest than clang, llvm etc?

```
~ ❯ which clang
/usr/bin/clang

~ ❯ clang --version
clang version 3.8.1 (tags/RELEASE_381/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

~ ❯ clang -v
clang version 3.8.1 (tags/RELEASE_381/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/6.2.1
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.2.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/6.2.1
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.2.1
Candidate multilib: .;@m64
Selected multilib: .;@m64

~ ❯ which gcc
/usr/bin/gcc

~ ❯ gcc --version
gcc (GCC) 6.2.1 20160830
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

~ ❯ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.2.1 20160830 (GCC) 
```

because the other plugins work well for me. `.clang_complete` contains -

```
-I./include
-stdlib=libc++
```

Are you using the extension-market installed extension as I am?

**Comment by kube** [comment]
The one I use in the video is the one from the Marketplace.

Did you try to specify `-std=c++11`?

I will check this as soon as I can, but the first thing I should do is to write tests, and provide output for debugging in issues like this.

**Comment by agauniyal** [comment]
Yes I did specify that option. Still didn't worked :disappointed: . For now I'm using you-complete-me for vscode plugin, however I'll check back in a while :smile:

**Comment by Nax** [comment]
You're using quote-style includes. They look for files in the same directory before falling back on the provided include paths. As the file is read from `stdin`, the includes are not correct anymore.

@kube You should investigate how clang behaves when reading files from stdin. It's probably possible to tell it what the file's directory is supposed to be. Maybe a simple `chdir` to the file's directory before starting clang would do the trick.

Also, you should stop using `-cc1` and escape the low-level clang options with `-Xclang`.
