### ISSUE TITLE
Set default stdlib to libc++ instead of libstdc++

### ISSUE THREAD

**Issue by kube** [kube/vscode-clang-complete#11]
Clang completion seems to use `libstdc++` by default instead of `libc++`, which causes problem when using C++11 features as reported in #10.

**Comment by Nax** [comment]
This should not cause problems unless the project uses very recent C++17 features.

**Comment by kube** [comment]
`<chrono>` does not seem to exist when using `libstdc++` as denoted in #10.

http://www.cplusplus.com/reference/chrono/

**Comment by Nax** [comment]
It does.

https://gcc.gnu.org/onlinedocs/libstdc++/libstdc++-api-4.5/a00785_source.html

The issue is probably related to the way `-cc1` ignores default include paths.
