### ISSUE TITLE
Enable C++ files

### ISSUE THREAD

**Issue by kube** [kube/vscode-clang-complete#3]

**Comment by zonyitoo** [comment]
Is this supported yet?

**Comment by kube** [comment]
Not supported at the moment.
But I'm gonna fix this this week, it's my priority on this project.

**Comment by CaiusTSM** [comment]
Are we there yet? :^)

I want this so bad, thank you for making this extension.

**Comment by kube** [comment]
C++ completion is not the problem here, I have it working already.
The issue I have is that the LanguageServer module from Microsoft does not permit me easily to set options to the server, and I cannot rely on the file extension to chose the compilation language for Clang. (A file can have no extension, and be set in C language syntax in the editor)

I will go further tomorrow night to see how I can make this work, but having another project working on now, I can work on it just on my extra time.

Sorry for the delay.

**Comment by agauniyal** [comment]
👍 Looking forward to this plugin :)

**Comment by kube** [comment]
Nice to see that some people are still interested in it. :)
Now that Microsoft really improved their extension system I'm gonna try to make it work as it should.

**Comment by agauniyal** [comment]
IMO this is the only plugin that has been implemented properly. The c/cpp plugin from Microsoft doesn't provide context aware semantic completions, but only provides completions from keywords present in files. There's another clang plugin in market place which works quite well but isn't implemented as language server plugin, which would make it bad to work with large files. And there are lots of people looking for c++ completion and hence interested in this plugin :)

**Comment by kube** [comment]
I reworked the extension to be more simple, enhanced completion, and fixed some stuff.
I still have a lot of things to do on it, code is not really elegant.

I have a problem when trying to compile it before pushing to VSCode MarketPlace, so I will push it tomorrow after fixing it.

I would really like to have your comments on what features you would like as a C++ user on this extension.
For now there's no linter, the extension simply provides completion, but I'm gonna work on new features after this, to provide something more Intellisense-like.

**Comment by kube** [comment]
The new version is now available on the Marketplace.

**Comment by agauniyal** [comment]
Some of the features I could think of is - 
- support for compile_commands.json file. It is produced by almost every c++ build system including cmake, meson, conan and the others. It looks something like this, and replaces need for .clang_complete file -

```
[
{
  "directory": "/user/name/build_dir/sub_dir",
  "command": "/usr/local/bin/clang++    -stdlib=libc++ -std=c++1z -Wall -Wextra -Wdocumentation -pedantic -g3 -fomit-frame-pointer -O0 -fno-inline -o CMakeFiles/sub_dir/file1.cpp.o -c /user/name/source_dir/sub_dir/file1.cpp",
  "file": "/user/name/source_dir/sub_dir/file1.cpp"
},
{
  "directory": "/user/name/build_dir/sub_dir",
  "command": "/usr/local/bin/clang++    -stdlib=libc++ -std=c++1z -Wall -Wextra -Wdocumentation -pedantic -g3 -fomit-frame-pointer -O0 -fno-inline -o CMakeFiles/sub_dir/file2.cpp.o -c /user/name/source_dir/sub_dir/file2.cpp",
  "file": "/user/name/source_dir/sub_dir/file2.cpp"
}
]
```

For system configuration which don't support using this, there are tools like [Bear](https://github.com/rizsotto/Bear) and others too. Here you can find more info - http://clang.llvm.org/docs/JSONCompilationDatabase.html
- function parameter completion, probably like [this](https://i.github-camo.com/771427526279fb2b8199a08acf6ba1edc0247af7/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f7961737579756b792f6175746f636f6d706c6574652d636c616e672f446f63756d656e74496d6167652f696d616765732f6175746f636f6d706c6574652d636c616e672e676966). 
- a basic linter pointing to which lines are showing what errors.

Infact there's another amazing c/c++ completion engine that I use with vim, which also uses clang as backend for completion. You could get ideas by looking at its features - https://github.com/Valloric/YouCompleteMe . And it provides all its functionality via editor agnostic backend too - https://github.com/Valloric/ycmd

**Comment by agauniyal** [comment]
Also I tried your plugin but failed to successfully use it. It wasn't showing completions and marking my class's object as `int` type 😕 

Here are few errors - 

```
[Error - 2:41:20 PM] Request completionItem/resolve failed.
  Message: Unhandled method completionItem/resolve
  Code: -32601 
[Error - 2:41:20 PM] Request completionItem/resolve failed.
  Message: Unhandled method completionItem/resolve
  Code: -32601 
[Error - 2:41:29 PM] Request completionItem/resolve failed.
  Message: Unhandled method completionItem/resolve
  Code: -32601 
[Error - 2:41:31 PM] Request completionItem/resolve failed.
  Message: Unhandled method completionItem/resolve
  Code: -32601 
[Error - 2:41:49 PM] Request completionItem/resolve failed.
  Message: Unhandled method completionItem/resolve
  Code: -32601 
[Error - 2:41:51 PM] Request completionItem/resolve failed.
  Message: Unhandled method completionItem/resolve
  Code: -32601 
[Error - 2:41:57 PM] Request completionItem/resolve failed.
  Message: Unhandled method completionItem/resolve
  Code: -32601 
[Error - 2:43:02 PM] Request completionItem/resolve failed.
  Message: Unhandled method completionItem/resolve
  Code: -32601 
[Error - 2:43:06 PM] Request completionItem/resolve failed.
  Message: Unhandled method completionItem/resolve
  Code: -32601 
[Error - 2:43:07 PM] Request completionItem/resolve failed.
  Message: Unhandled method completionItem/resolve
  Code: -32601 
[Error - 2:43:16 PM] Request completionItem/resolve failed.
  Message: Unhandled method completionItem/resolve
  Code: -32601 
[Error - 2:43:24 PM] Request completionItem/resolve failed.
  Message: Unhandled method completionItem/resolve
  Code: -32601 
[Error - 2:43:25 PM] Request completionItem/resolve failed.
  Message: Unhandled method completionItem/resolve
  Code: -32601 

```

**Comment by kube** [comment]
Just to be sure, are you on macOS Sierra Beta ?
I am, and I had issues caused by libevent that cannot be fixed until they update Electron.
I had these issues during testing, and I thought it was linked to the libevent issue, but I still could complete text while leaving the bottom panel open.

**Comment by agauniyal** [comment]
I'm on Linux. My system-wide installation of electron is v1.3.5, but I doubt they use it. They must be bundling their own electron, and thus I'm on VSCode 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877).

**Comment by kube** [comment]
Ok so it comes from my code.
I updated dependencies, and some were installed in `-next` version by default. (`vscode-languageserver` and `vscode-languageclient`)
I'm gonna look at this.

**Comment by kube** [comment]
Ok it's now fixed and on the Marketplace.
I'm gonna close this issue as it's working on my side.
Don't hesitate to re-open or comment it if you have a problem.
And do not hesitate to open issues for features or bugs on the repo.
